### ISSUE TITLE
check test_agreement function

### ISSUE THREAD

**Issue by peterlevy** [NERC-CEH/ukem#5]
The test_agreement function shows close agreement between output maps and national totals in 2019, but these diverge in earlier years.  We need to check that the totals from the output maps are correct.

**Comment by peterlevy** [comment]
If you run the targets, you will have identical outputs.  We don't need to store them on GitHub because the code guarantees that they will be the same.

**Comment by oSamTo** [comment]
works ok for me back to 2010; 

$`2010`
      ch4       n2o       co2 
0.9748705 0.9703654 0.9729012 

$`2011`
      ch4       n2o       co2 
0.9720374 0.9717709 0.9797694 

$`2012`
      ch4       n2o       co2 
0.9722882 0.9706301 0.9729111 

$`2013`
      ch4       n2o       co2 
0.9722841 0.9707903 0.9726540 

$`2014`
      ch4       n2o       co2 
0.9723612 0.9705801 0.9727516 

$`2015`
      ch4       n2o       co2 
0.9725600 0.9705826 0.9750852 

$`2016`
      ch4       n2o       co2 
0.9725230 0.9708959 0.9785536 

$`2017`
      ch4       n2o       co2 
0.9723500 0.9709020 0.9771152 

$`2018`
      ch4       n2o       co2 
0.9723774 0.9708832 0.9739001 

$`2019`
      ch4       n2o       co2 
0.9725698 0.9710396 0.9738448
